workflows:
   android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      java: 17
      # android_signing:
      #   - kl_keystore
      groups:
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      vars:
        PACKAGE_NAME: "szk.challange.kawanlama" # <-- Put your package name here
        GOOGLE_PLAY_TRACK: "internal"
      flutter: 3.24.1
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Upgrade major version
        script: |
          flutter pub upgrade --major-versions
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build APK with Flutter
        script: |
          echo "Tag: $CI_TAG"
          BUILD_NUMBER=${CI_TAG##*+}
          echo "Extracted build number: $BUILD_NUMBER"
          sed -i.bak 's/^ *version:.*$/version: 1.0.0+'$BUILD_NUMBER'/' pubspec.yaml
          echo "$BUILD_NUMBER"
          echo "$CM_KEY_ALIAS"
          flutter build appbundle --release -v \
            --build-name=1.0.$BUILD_NUMBER \
            --build-number=$BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - yudhistiray198@gmail.com
        notify:
          success: true
          failure: false
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: true
