workflows:
   android-workflow:
    name: Android Workflow
    instance_type: mac_mini_m1
    max_build_duration: 120
    triggering:
      events:
        - tag
      tag_patterns:
        - pattern: 'v*'
          include: true
    environment:
      java: 17
      # android_signing:
      #   - kl_keystore
      groups:
        - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS)
      vars:
        PACKAGE_NAME: "szk.challange.kawanlama" # <-- Put your package name here
        GOOGLE_PLAY_TRACK: "internal"
      flutter: 3.24.1
    scripts:
      - name: Set up local.properties
        script: |
          echo "flutter.sdk=$HOME/programs/flutter" > "$CM_BUILD_DIR/android/local.properties"
      - name: Upgrade major version
        script: |
          flutter pub upgrade --major-versions
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Get version and auto-increment build number
        script: |
          git fetch --tags

          # Get the latest tag or fallback
          export GIT_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "v1.0.0+59")
          echo "Latest Git tag: $GIT_TAG"

          # Remove the 'v' prefix
          export VERSION_FULL=${GIT_TAG#v}

          # Extract version name and build number
          export VERSION_NAME=$(echo $VERSION_FULL | cut -d'+' -f1)
          export BUILD_NUMBER=$(echo $VERSION_FULL | cut -d'+' -f2)
          export OLD_BUILD_NUMBER_GOOGLE=$(($(google-play get-latest-build-number --package-name "$PACKAGE_NAME" --tracks="$GOOGLE_PLAY_TRACK")))

          # Increment build number (add 10)
          export NEW_BUILD_NUMBER=$((OLD_BUILD_NUMBER_GOOGLE + BUILD_NUMBER))

          echo "Version name: $VERSION_NAME"
          echo "Old build number: $OLD_BUILD_NUMBER_GOOGLE"
          echo "New build number: $NEW_BUILD_NUMBER"

          # Update pubspec.yaml
          sed -i.bak "s/^version: .*/version: $VERSION_NAME+$NEW_BUILD_NUMBER/" pubspec.yaml
      - name: Build APK with Flutter
        script: |
          flutter build apk --release -v \
            --build-name=1.0.0 \
            --build-number=$NEW_BUILD_NUMBER
    artifacts:
      - build/**/outputs/**/*.aab
      - build/**/outputs/**/mapping.txt
      - flutter_drive.log
    publishing:
      email:
        recipients:
          - yudhistiray198@gmail.com
        notify:
          success: true
          failure: false
